# Step 1: Use an official Python runtime as a parent image
FROM python:3.8-slim
# Step 2: Set the working directory in the container
WORKDIR /usr/src/main
# Step 3: Copy the requirements.txt file into the container
COPY requirements.txt ./
# Step 4: Install the required Python packages
RUN pip install --no-cache-dir -r requirements.txt
# Step 5: Copy the current directory contents into the container
COPY . .
# Step 6: Expose the application port
EXPOSE 7001
# Step 7: Define the command to run the Flask app
CMD [ "python", "./main.py" ]